version: '2.3'
services:
  db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peertube
      POSTGRES_PASSWORD: peertube
      POSTGRES_DB: peertube_prod

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis:/data

  caddy:
    image: yukimochi/container-caddy:edge
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./caddy/cert:/.caddy
      - ./caddy/conf:/etc/caddy
      - ./caddy/logs:/var/log/caddy
      - ./storage:/webroot/storage
      - client:/client
    depends_on:
      - app
      - initializer

  initializer:
    build: .
    image: yukimochi/peertube:latest
    restart: on-failure:2
    user: root
    command: cp -r /var/www/peertube/client/dist /
    volumes:
      - client:/dist

  app:
    build: .
    image: yukimochi/peertube:latest
    restart: always
    user: root
    depends_on:
      - db
      - redis
    volumes:
      - ./app/config/production.yaml:/var/www/peertube/config/production.yaml
      - ./storage:/var/www/peertube/storage

volumes:
  client:
    driver: local
